### ISSUE TITLE
Issue about personachat_data_dir

### ISSUE THREAD

**Issue by Zhouziyi828** [passing2961/PersonaChatGen#1]
In ProfilePromptGenerator, it seems that the argument "personachat_data_dir" is missed. When I run the profile_main.py, the error: TypeError: __init__() missing 1 required positional argument: 'personachat_data_dir' appeared.

Thanks again for your open code.

**Comment by passing2961** [comment]
Thanks for the feedback :)

We will correct and update it ASAP :)
